<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class ConsultantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $consultants = [
            [
                'name' => 'Sarah Martinez',
                'first_name' => 'Sarah',
                'last_name' => 'Martinez',
                'username' => 'sarah.martinez',
                'email' => 'demo@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 12 34 56 78',
                'whatsapp' => '+212 6 12 34 56 78',
                'address' => '123 Rue Mohammed V',
                'city' => 'Casablanca',
                'country' => 'Morocco',
                'bio' => 'Full Stack Developer with 8+ years of experience in building scalable web applications. Specialized in React, Node.js, and cloud architectures.',
                'title' => 'Senior Full Stack Developer',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Sarah+Martinez&size=200&background=3B82F6&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 450.00,
                'portfolio' => json_encode([
                    ['title' => 'E-commerce Platform', 'description' => 'Built a complete e-commerce solution with React and Node.js'],
                    ['title' => 'Healthcare Management System', 'description' => 'Developed a patient management system for hospitals'],
                    ['title' => 'Real-time Chat Application', 'description' => 'Created a scalable chat app using WebSocket']
                ]),
                'linkedin' => 'https://linkedin.com/in/sarahmartinez',
                'github' => 'https://github.com/sarahmartinez',
                'twitter' => 'https://twitter.com/sarahdev',
                'website' => 'https://sarahmartinez.dev',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Ahmed El Fassi',
                'first_name' => 'Ahmed',
                'last_name' => 'El Fassi',
                'username' => 'ahmed.elfassi',
                'email' => 'ahmed.elfassi@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 23 45 67 89',
                'whatsapp' => '+212 6 23 45 67 89',
                'address' => '45 Avenue Hassan II',
                'city' => 'Rabat',
                'country' => 'Morocco',
                'bio' => 'UI/UX Designer passionate about creating beautiful and intuitive user experiences. Expertise in Figma, Adobe XD, and user research.',
                'title' => 'Senior UI/UX Designer',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Ahmed+ElFassi&size=200&background=8B5CF6&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 380.00,
                'portfolio' => json_encode([
                    ['title' => 'Mobile Banking App', 'description' => 'Redesigned mobile banking experience for major bank'],
                    ['title' => 'SaaS Dashboard', 'description' => 'Created intuitive dashboard for analytics platform'],
                    ['title' => 'Travel Booking Website', 'description' => 'Designed user-friendly travel booking interface']
                ]),
                'linkedin' => 'https://linkedin.com/in/ahmedelfassi',
                'github' => 'https://github.com/ahmedelfassi',
                'twitter' => 'https://twitter.com/ahmeddesign',
                'website' => 'https://ahmedelfassi.design',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Jennifer Wong',
                'first_name' => 'Jennifer',
                'last_name' => 'Wong',
                'username' => 'jennifer.wong',
                'email' => 'jennifer.wong@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 34 56 78 90',
                'whatsapp' => '+212 6 34 56 78 90',
                'address' => '78 Boulevard Zerktouni',
                'city' => 'Casablanca',
                'country' => 'Morocco',
                'bio' => 'Data Scientist and Machine Learning Engineer with expertise in Python, TensorFlow, and predictive modeling. Published researcher in AI.',
                'title' => 'Lead Data Scientist',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Jennifer+Wong&size=200&background=10B981&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 520.00,
                'portfolio' => json_encode([
                    ['title' => 'Customer Churn Prediction', 'description' => 'Built ML model predicting customer churn with 92% accuracy'],
                    ['title' => 'Image Recognition System', 'description' => 'Developed computer vision system for quality control'],
                    ['title' => 'Recommendation Engine', 'description' => 'Created personalized recommendation algorithm']
                ]),
                'linkedin' => 'https://linkedin.com/in/jenniferwong',
                'github' => 'https://github.com/jenniferwong',
                'twitter' => 'https://twitter.com/jenwongdata',
                'website' => 'https://jenniferwong.ai',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Mohammed Alami',
                'first_name' => 'Mohammed',
                'last_name' => 'Alami',
                'username' => 'mohammed.alami',
                'email' => 'mohammed.alami@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 45 67 89 01',
                'whatsapp' => '+212 6 45 67 89 01',
                'address' => '12 Rue Ibn Khaldoun',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'bio' => 'DevOps Engineer specializing in cloud infrastructure, CI/CD pipelines, and containerization. AWS & Azure certified.',
                'title' => 'Senior DevOps Engineer',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Mohammed+Alami&size=200&background=F59E0B&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 410.00,
                'portfolio' => json_encode([
                    ['title' => 'Cloud Migration', 'description' => 'Led migration of legacy system to AWS cloud infrastructure'],
                    ['title' => 'CI/CD Pipeline', 'description' => 'Implemented automated deployment pipeline reducing release time by 80%'],
                    ['title' => 'Kubernetes Cluster', 'description' => 'Designed and deployed production-grade Kubernetes cluster']
                ]),
                'linkedin' => 'https://linkedin.com/in/mohammedalami',
                'github' => 'https://github.com/mohammedalami',
                'twitter' => 'https://twitter.com/modevops',
                'website' => 'https://mohammedalami.cloud',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Lisa Chen',
                'first_name' => 'Lisa',
                'last_name' => 'Chen',
                'username' => 'lisa.chen',
                'email' => 'lisa.chen@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 56 78 90 12',
                'whatsapp' => '+212 6 56 78 90 12',
                'address' => '34 Avenue des FAR',
                'city' => 'Tangier',
                'country' => 'Morocco',
                'bio' => 'Mobile App Developer with 6 years of experience in iOS and Android development. Expert in React Native and Flutter.',
                'title' => 'Mobile App Developer',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Lisa+Chen&size=200&background=EF4444&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 390.00,
                'portfolio' => json_encode([
                    ['title' => 'Fitness Tracking App', 'description' => 'Built cross-platform fitness app with 100k+ downloads'],
                    ['title' => 'Food Delivery App', 'description' => 'Developed real-time order tracking mobile application'],
                    ['title' => 'Social Media App', 'description' => 'Created social networking app with chat and media sharing']
                ]),
                'linkedin' => 'https://linkedin.com/in/lisachen',
                'github' => 'https://github.com/lisachen',
                'twitter' => 'https://twitter.com/lisachendev',
                'website' => 'https://lisachen.mobile',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Karim Bennani',
                'first_name' => 'Karim',
                'last_name' => 'Bennani',
                'username' => 'karim.bennani',
                'email' => 'karim.bennani@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 67 89 01 23',
                'whatsapp' => '+212 6 67 89 01 23',
                'address' => '56 Rue Allal Ben Abdellah',
                'city' => 'Fes',
                'country' => 'Morocco',
                'bio' => 'Cybersecurity Consultant with expertise in penetration testing, security audits, and compliance. CISSP certified.',
                'title' => 'Cybersecurity Consultant',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Karim+Bennani&size=200&background=6366F1&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 480.00,
                'portfolio' => json_encode([
                    ['title' => 'Security Audit', 'description' => 'Conducted comprehensive security audit for financial institution'],
                    ['title' => 'Penetration Testing', 'description' => 'Performed ethical hacking to identify vulnerabilities'],
                    ['title' => 'GDPR Compliance', 'description' => 'Led GDPR compliance implementation for enterprise']
                ]),
                'linkedin' => 'https://linkedin.com/in/karimbennani',
                'github' => 'https://github.com/karimbennani',
                'twitter' => 'https://twitter.com/karimsec',
                'website' => 'https://karimbennani.security',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Emily Thompson',
                'first_name' => 'Emily',
                'last_name' => 'Thompson',
                'username' => 'emily.thompson',
                'email' => 'emily.thompson@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 78 90 12 34',
                'whatsapp' => '+212 6 78 90 12 34',
                'address' => '89 Boulevard Mohammed VI',
                'city' => 'Agadir',
                'country' => 'Morocco',
                'bio' => 'Digital Marketing Strategist specializing in SEO, content marketing, and social media campaigns. Certified Google Analytics expert.',
                'title' => 'Digital Marketing Consultant',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Emily+Thompson&size=200&background=EC4899&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 350.00,
                'portfolio' => json_encode([
                    ['title' => 'SEO Campaign', 'description' => 'Increased organic traffic by 300% for e-commerce client'],
                    ['title' => 'Social Media Strategy', 'description' => 'Grew Instagram following from 5k to 100k in 6 months'],
                    ['title' => 'Content Marketing', 'description' => 'Created content strategy resulting in 5x lead generation']
                ]),
                'linkedin' => 'https://linkedin.com/in/emilythompson',
                'github' => null,
                'twitter' => 'https://twitter.com/emilymarketing',
                'website' => 'https://emilythompson.marketing',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Youssef Idrissi',
                'first_name' => 'Youssef',
                'last_name' => 'Idrissi',
                'username' => 'youssef.idrissi',
                'email' => 'youssef.idrissi@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 89 01 23 45',
                'whatsapp' => '+212 6 89 01 23 45',
                'address' => '23 Avenue Lalla Yacout',
                'city' => 'Casablanca',
                'country' => 'Morocco',
                'bio' => 'Blockchain Developer with expertise in Ethereum, Solidity, and DeFi applications. Built multiple successful NFT and DApp projects.',
                'title' => 'Blockchain Developer',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Youssef+Idrissi&size=200&background=14B8A6&color=fff',
                'available_for_hire' => false,
                'hourly_rate' => 550.00,
                'portfolio' => json_encode([
                    ['title' => 'NFT Marketplace', 'description' => 'Developed decentralized NFT marketplace on Ethereum'],
                    ['title' => 'DeFi Protocol', 'description' => 'Built lending protocol with smart contracts'],
                    ['title' => 'Token Launch', 'description' => 'Created and launched ERC-20 token with tokenomics']
                ]),
                'linkedin' => 'https://linkedin.com/in/youssefidrissi',
                'github' => 'https://github.com/youssefidrissi',
                'twitter' => 'https://twitter.com/youssefdao',
                'website' => 'https://youssefidrissi.crypto',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Sophia Rodriguez',
                'first_name' => 'Sophia',
                'last_name' => 'Rodriguez',
                'username' => 'sophia.rodriguez',
                'email' => 'sophia.rodriguez@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 90 12 34 56',
                'whatsapp' => '+212 6 90 12 34 56',
                'address' => '67 Rue de la Liberté',
                'city' => 'Rabat',
                'country' => 'Morocco',
                'bio' => 'Product Manager with 10+ years of experience leading successful product launches. Expert in Agile methodologies and user research.',
                'title' => 'Senior Product Manager',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Sophia+Rodriguez&size=200&background=DC2626&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 460.00,
                'portfolio' => json_encode([
                    ['title' => 'SaaS Product Launch', 'description' => 'Led launch of B2B SaaS product reaching $5M ARR in first year'],
                    ['title' => 'Mobile App Redesign', 'description' => 'Managed complete redesign improving user retention by 40%'],
                    ['title' => 'Feature Roadmap', 'description' => 'Created 12-month product roadmap based on user research']
                ]),
                'linkedin' => 'https://linkedin.com/in/sophiarodriguez',
                'github' => null,
                'twitter' => 'https://twitter.com/sophiapm',
                'website' => 'https://sophiarodriguez.product',
                'role' => 'consultant',
                'status' => 'active',
            ],
            [
                'name' => 'Omar Chakir',
                'first_name' => 'Omar',
                'last_name' => 'Chakir',
                'username' => 'omar.chakir',
                'email' => 'omar.chakir@consultant.com',
                'password' => Hash::make('123456789'),
                'phone' => '+212 6 01 23 45 67',
                'whatsapp' => '+212 6 01 23 45 67',
                'address' => '91 Avenue Moulay Youssef',
                'city' => 'Meknes',
                'country' => 'Morocco',
                'bio' => 'Business Analyst and Project Manager with MBA and PMP certification. Specialized in digital transformation and process optimization.',
                'title' => 'Senior Business Analyst',
                'profile_picture' => 'https://ui-avatars.com/api/?name=Omar+Chakir&size=200&background=7C3AED&color=fff',
                'available_for_hire' => true,
                'hourly_rate' => 400.00,
                'portfolio' => json_encode([
                    ['title' => 'Digital Transformation', 'description' => 'Led digital transformation project for manufacturing company'],
                    ['title' => 'Process Optimization', 'description' => 'Optimized business processes reducing costs by 35%'],
                    ['title' => 'ERP Implementation', 'description' => 'Managed enterprise ERP system implementation']
                ]),
                'linkedin' => 'https://linkedin.com/in/omarchakir',
                'github' => null,
                'twitter' => 'https://twitter.com/omarbiz',
                'website' => 'https://omarchakir.business',
                'role' => 'consultant',
                'status' => 'active',
            ],
        ];

        foreach ($consultants as $consultant) {
            User::create($consultant);
        }
    }
}
